server:
  port: 8090
  servlet:
    session:
      timeout: 259200m

spring:
  mvc:
    static-path-pattern: /**
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://rm-cn-4xl3gmscg000cxpo.rwlb.rds.aliyuncs.com:3306/spm_db?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: Root123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: com.spm1.mapper.*Mapper
  configuration:
    mapUnderscoreToCamelCase: false
  type-aliases-package: com.spm1.entity
  global-config:
    refresh-mapper: true
    column-underline: true